language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev" # 3.5 development branch
  - "3.6-dev" # 3.6 development branch
  - "nightly" # currently points to 3.7-dev
install:
  - pip install coveralls
  - pip install codecov
# command to run tests
script:
  coverage run --source=class_namespaces -m pytest
after_success:
  - coveralls
  - codecov
addons:
    code_climate:
        repo_token: 3d0451505f214ce48df076eef5d02e4b606a6be6eea4e3ca70cbbb56e24270fd
